# Generated by Django 5.2.7 on 2025-10-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_objects', models.IntegerField()),
                ('processed_objects', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TOIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toi_id', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('confidence', models.CharField(max_length=10)),
                ('feature_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classifier.classificationjob')),
            ],
        ),
    ]
