# Generated by Django 5.2.7 on 2025-10-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationjob',
            name='file_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
