# Generated by Django 5.2.7 on 2025-10-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_classificationjob_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toiresult',
            name='tic_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
